spring:
  application:
    name: ms-customer

server:
  port: ${SERVER_PORT:8930}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}

#bootstrap.properties

#bootstrap.properties
#application.yml


